#:kivy 1.0.9


    
<Display>:
    
    text: "press me!"

    canvas:
        Rectangle:
            pos: self.pos
            size: self.size

<Timer>:
    text: "I'm a clock"
    Button:
        id: timerButton
        text: "Click to reset timer"
        on_press: root.button_clicked()

<MainScreen@BoxLayout>
    timerDisplay: timer


    BoxLayout:
        orientation: 'vertical'
        size_hint: .33, 1
       
        

        id: home
        counter: 0

        Label:
            id: label1
            text: "hello world!"
            halign: 'center'
            valign: 'middle'

        Button:
            id: button1
            text: "click me!"
            halign: 'center'
            valign: 'middle'
            on_press: root.button_clicked()
    BoxLayout:
        orientation: 'vertical' 
        size_hint: .67, 1
        id: rightScreen


        Display:
            
    
        Display:
        Timer:
            id: timer
        Label:
            text: "Time elapsed: " + str(root.timerDisplay.mTime)
            
        Label:
            id: accel1
            text: "Let's say... Acceleration"
BoxLayout:
    orientation: 'horizontal'
    padding: 20
    spacing: 10
    MainScreen:
        canvas:
            Rectangle:
                pos: self.pos
                size: self.size
    


    


    


   


        
