#ifndef __RFM69_H
#define __RFM69_H

// Autogenerated RFM69 headers generated with ICRDL tool
#include "rfm69_rdl.h"

void rfm69_init(*SPID SPID);
void rfm69_config(*SPID SPID);
int rfm69_test(*SPID SPID);

int rfm69_mode(*SPID SPID, uint8_t mode);

int rfm69_frame_rx(*SPID SPID, uint8_t *buf, int maxlen, uint8_t *rssi);
void rfm69_frame_tx(*SPID SPID, uint8_t *buf, int len);

uint8_t rfm69_register_read (*SPID SPID, uint8_t reg_addr);
void rfm69_register_write (*SPID SPID, uint8_t reg_addr, uint8_t reg_value);

uint8_t rfm69_payload_ready(*SPID SPID);
uint8_t rfm69_temperature(*SPID SPID);

// Interface with SPI bus
void rfm69_nss_assert(*SPID SPID);
void rfm69_nss_deassert(*SPID SPID);
uint8_t rfm69_spi_transfer_byte (*SPID SPID, uint8_t b);


/*
// Debug functions
void rfm69_register_print(void);
void rfm69_config_print(void);
void rfm69_config_verify(void);
void rfm69_showirqreg (void);
*/
#endif /* end __RFM69_H */
