#ifndef __RFM69_H
#define __RFM69_H

// Autogenerated RFM69 headers generated with ICRDL tool
#include "rfm69_rdl.h"
#include "ch.h"

/* Log data to the Radio.
* The channel is 0 to 255.
* Data is either char* (the first 8 bytes will be copied),
* or a number of integers that add up to 64 bits.
* The time the function is called is stored against the sample.
*/

void rfm69_log_c(uint8_t channel, const char* data);
void rfm69_log_s64(uint8_t channel, int64_t data);
void rfm69_log_s32(uint8_t channel, int32_t data_a, int32_t data_b);
void rfm69_log_s16(uint8_t channel, int16_t data_a, int16_t data_b,
									int16_t data_c, int16_t data_d);
void rfm69_log_u16(uint8_t channel, uint16_t data_a, uint16_t data_b,
									uint16_t data_c, uint16_t data_d);
void rfm69_log_f(uint8_t channel, float data_a, float data_b);


/*RFM69 Thread*/
msg_t rfm69_thread(void* arg);
msg_t rfm69_test_thread(void* arg);


#endif /* end __RFM69_H */
