#ifndef __RFM69_H
#define __RFM69_H

// Autogenerated RFM69 headers generated with ICRDL tool
#include "rfm69_rdl.h"
#include "ch.h"

/* Send a test packet with `data` in the last 8 bytes. */
void rfm69_send_test_packet(const char* data);

/* Log a pre-made packet to the radio. Must be a pointer to 16 bytes of memory.
 */
void rfm69_log_packet(uint8_t* packet);


/*RFM69 Thread*/
msg_t rfm69_thread(void* arg);


#endif /* end __RFM69_H */
